module.exports = [
  {
    iconName: 'FaUserAstronaut',
    name: '정혜정',
    photoName: 'sophie',
    job: '해외영업/국내영업/무역실무',
    specialty: '영어면접/실무면접',
    ex1: '(전) KOTRA 런던지사 대리',
    ex2: '(전) DHL International',
    ex3: '(전) 포스코 광석구매팀',
    ex4: '토익 990점/ OPIC 최고등급',
  },
  {
    iconName: 'FaUserAstronaut',
    name: '김형종',
    photoName: 'jong',
    job: '마케팅/해외영업/국내영업',
    specialty: '영어면접/실무면접',
    ex1: '(전) CJ제일제당 마케팅팀 대리',
    ex2: '(전) 롯데푸드 마케팅팀 대리',
    ex3: '(전) Henkel 마케팅팀 대리',
    ex4: 'University of New South Wales',
  },
  {
    iconName: 'FaUserAstronaut',
    name: '크리스 애쉬',
    photoName: 'chris',
    job: 'SW개발',
    specialty: '인성면접/실무면접',
    ex1: '(전) 네이버 안드로이드 개발',
    ex2: '(전) 웍스모바일 안드로이드 개발',
    ex3: '(전) Pantech 안드로이드 개발',
    ex4: '(전) Pantech 안드로이드 개발',
  },
  {
    iconName: 'FaUserAstronaut',
    name: '폴 마케비셔스',
    photoName: 'paul',
    job: 'SW개발/SW설계',
    specialty: '인성면접/실무면접',
    ex1: '(전) 한화테크윈',
    ex2: '(전) 삼성테크윈',
    ex3: '서울대학교 전기 및 전자공학 전공',
    ex4: '(전) Pantech 안드로이드 개발',
  },
];
