export const FETCH_USER = 'FETCH_USER';
export const AUTH_ERROR_CODE = 'AUTH_ERROR_CODE';
export const SIGN_OUT = 'SIGN_OUT';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SUBMIT_PRO = 'SUBMIT_PRO';
export const FETCH_PRO = 'FETCH_PRO';

// Photographers Action Types
export const CREATE_PHOTOGRAPHER = 'CREATE_PHOTOGRAPHER';
export const FETCH_PHOTOGRAPHERS = 'FETCH_PHOTOGRAPHERS';
export const FETCH_PHOTOGRAPHER = 'FETCH_PHOTOGRAPHER';
export const EDIT_PHOTOGRAPHER = 'EDIT_PHOTOGRAPHER';
export const DELETE_PHOTOGRAPHER = 'DELETE_PHOTOGRAPHER';
